name: Linux-mainline Arch Linux CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: |
          pacman -Syu --noconfirm base-devel git
          useradd user -mG wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          git clone https://aur.archlinux.org/linux-mainline.git
          chown user -R .
          cd linux-mainline
          su user -c "yes|PKGDEST=/tmp/linux-mainline makepkg --noconfirm -s"
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-mainline
          path: /tmp/linux-mainline
